B_period: 10.0
C_period: 20.0
D_period: 10.0
MAX_MRNA_PER_GENE: 10000
N_target_cells: 1000
N_target_samples: 100000
Nf_amp: 0.23761592408148383
Nf_base: 1.5118216247002567
Nf_birth: 1.0
Nf_global: 1.5118216247002567
Nf_max: null
Nf_min: 1.0e-09
Nf_mode: operon_scaled
Nf_period: 40.0
Nf_phase: 0
Nf_type: sine
T_div: 40.0
chromosome_length_bp: 4600000
dt: 0.1
mode: stochastic
random_seed: 1
