B_period: 10.0
C_period: 20.0
D_period: 10.0
MAX_MRNA_PER_GENE: 10000
N_target_samples: 100000
T_div: 40.0
T_total: 680.0
chromosome_length_bp: 4600000
division_time_cv: 0.05
division_time_max: 44.0
division_time_max_attempts: 1000
division_time_method: clip
division_time_min: 36.0
dt: 0.1
genes_path: random_genes.csv
initial_cell_count: 3
measured_dist_path: S_params.json
nf_vector_path: nf_vector.npy
out_path: snapshots.csv
parsed_out_path: snapshots_parsed.csv
random_seed: 1
sparse: true
